version: '2'
services:
    app:
        build: .
        image: payment
        ports:
            - 8000:8000
        environment:
            APP_PORT: 8000
            DB_HOST: 127.0.0.1
            DB_PORT: 5432
            DB_USER: payments
            DB_PASSWORD: SecuredPassword
            DB_NAME: payments
            JAEGER_SERVICE_NAME: payment-api 
            JAEGER_AGENT_HOST: localhost 
            JAEGER_AGENT_PORT: 6831 
            JAEGER_SAMPLER_TYPE: const 
            JAEGER_SAMPLER_PARAM: 1 
        depends_on: 
            - db
            - jaeger

    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: payments
            POSTGRES_PASSWORD: SecuredPassword
  
    # UI for db management
    adminer:
        image: adminer
        ports:
            - 8080:8080

    # Tracing
    jaeger:
        image: jaegertracing/all-in-one:1.3.0
        ports:
        - 127.0.0.1:5775:5775/udp # accept zipkin.thrift over compact thrift protocol
        - 127.0.0.1:6831:6831/udp # accept jaeger.thrift over compact thrift protocol
        - 127.0.0.1:6832:6832/udp # accept jaeger.thrift over binary thrift protocol
        - 127.0.0.1:5778:5778 # serve configs
        - 127.0.0.1:16686:16686 # serve frontend
        - 127.0.0.1:14268:14268 # accept jaeger.thrift directly from clients