// Code generated by mockery v1.0.0. DO NOT EDIT.

// NOTE: run 'make update-mocks' from payment-api top folder to update this file and generate new ones.

package errorhandling

import mock "github.com/stretchr/testify/mock"

// MockAPIError is an autogenerated mock type for the APIError type
type MockAPIError struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *MockAPIError) Error() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
